### ISSUE TITLE
dimentio fails on Odyssey 1.2

### ISSUE THREAD

**Issue by Diatrus** [0x7ff/dimentio#8]
The only logging is as follows: 

```
iPhone:~ mobile% sudo dimentio
host: 0xC03
iPhone:~ mobile%
```

**Comment by 0x7ff** [comment]
Hey Diatrus,
I looked into it, they are trying to mimic tfp0 by replacing corpse_task->map with kernel_task->map and they added that port to realhost.special[4], but they seem to forgot patching it's PID value with 0. So I removed the PID check. My devices are all on iOS 14+, so I can't try this patch.

**Comment by Diatrus** [comment]
Fix works wonderfully, thank you.

**Comment by Halo-Michael** [comment]
> Fix works wonderfully, thank you.

It's not truly fix.

**Comment by Diatrus** [comment]
> > Fix works wonderfully, thank you.
> 
> It's not truly fix.

The reason this issue is open, is fixed.

**Comment by Halo-Michael** [comment]
Uh, the reason this issue comes from odyssey, is not fixed.
 _they are trying to mimic tfp0 by replacing corpse_task->map with kernel_task->map and they added that port to realhost.special[4], but they seem to forgot patching it's PID value with 0._
